# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      terraform:
        update-types:
          - "major"
          - "minor"
          - "patch"
    commit-message:
      prefix: "⬆️ tf:"

  - package-ecosystem: "gomod"
    directory: "/test"
    schedule:
      interval: "weekly"
    groups:
      test:
        update-types:
          - "major"
          - "minor"
          - "patch"
    commit-message:
      prefix: "⬆️ test:"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        update-types:
          - "major"
          - "minor"
          - "patch"
    commit-message:
      prefix: "⬆️ gha:"
