version = 1

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/bendoerr-terraform-modules/terraform-aws-defaults/test"
