name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  terratest:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: "Harden Runner"
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - name: "Checkout"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Setup Go"
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: test/go.mod
          cache: true

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 #v4.0.0

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-to-assume: arn:aws:iam::234656776442:role/brd-sndbx-ue1-core-apply
          aws-region: us-east-1

      - name: "Install JUnit Reporter"
        working-directory: test
        run: go install github.com/jstemmer/go-junit-report/v2@v2.1.0

      - name: "Run Tests"
        working-directory: test
        shell: bash
        run: go test -timeout 20m -v ./... 2>&1 | tee results.out

      - name: "Convert Test Results"
        working-directory: test
        shell: bash
        if: hashFiles('test/results.out') != ''
        run: go-junit-report -set-exit-code < results.out > results.xml

      - name: "Upload Test Results"
        uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86 # v2.4
        if: hashFiles('test/results.xml') != ''
        with:
          paths: test/results.xml
